Fiorella/Models/BaseEntity.cs
using System;
namespace Fiorella.Models
{
	public abstract class BaseEntity
	{
		public int Id { get; set; }
		public bool SoftDeleted { get; set; } = false;
		public DateTime CreatedDate { get; set; } = DateTime.Now;

	}
}

Fiorella/Models/Blog.cs
using System;
namespace Fiorella.Models
{
	public class Blog:BaseEntity
	{
		public string Title { get; set; }
		public string Description { get; set; }
		public string Image { get; set; }

	}
}

Fiorella/Models/Category.cs
using System;
namespace Fiorella.Models
{
	public class Category:BaseEntity
	{
		public string Name { get; set; }
		public ICollection<Product> Products { get; set; }

	}
}

Fiorella/Models/Expert.cs
using System;
namespace Fiorella.Models
{
	public class Expert:BaseEntity
	{
		public string FullName { get; set; }
		public string Image { get; set; }
		public string Position { get; set; }

	}
}

Fiorella/Models/Product.cs
using System;
namespace Fiorella.Models
{
	public class Product:BaseEntity
	{
		public string Name { get; set; }
		public decimal Price { get; set; }
		public string Description { get; set; }
		public int CategoryId { get; set; }
		public Category Category { get; set; }
		public ICollection<ProductImage> ProductImages { get; set; }

	}
}

Fiorella/Models/ProductImage.cs
using System;
namespace Fiorella.Models
{
	public class ProductImage
	{
		public int Id { get; set; }
		public string Name { get; set; }
		public bool  IsMain { get; set; }
		public int ProductId { get; set; }
		public Product Product { get; set; }

	}
}

Fiorella/Models/Slider.cs
using System;
namespace Fiorella.Models
{
	public class Slider:BaseEntity
	{
		public string Image { get; set; }


	}
}

Fiorella/Models/SliderInfo.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Fiorella.Models
{
	public class SliderInfo:BaseEntity
	{
		[Required]
		[StringLength(200)]
		public string Title { get; set; }
		[Required]
		[StringLength(200)]
		public string Description { get; set; }
		public string Image { get; set; }

	}
}

Fiorella/ViewModels/Blog/BlogVM.cs
using System;
namespace Fiorella.ViewModels.Blog
{
	public class BlogVM
	{
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public string CreatedDate { get; set; }
    }
}

Fiorella/ViewModels/Expert/ExpertVM.cs
using System;
namespace Fiorella.ViewModels.Expert
{
	public class ExpertVM
	{
        public string FullName { get; set; }
        public string Image { get; set; }
        public string Position { get; set; }
    }
}

Fiorella/ViewModels/HomeVM.cs
using System;
using Fiorella.Models;
using Fiorella.ViewModels.Blog;
using Fiorella.ViewModels.Expert;

namespace Fiorella.ViewModels
{
	public class HomeVM
	{
		public IEnumerable<Slider> Sliders { get; set; }
		public SliderInfo SliderInfo { get; set; }
		public IEnumerable<BlogVM> Blogs { get; set; }
		public IEnumerable<ExpertVM> Experts { get; set; }
		public IEnumerable<Category> Categories{ get; set; }
		public IEnumerable<Product> Products { get; set; }



	}
}

Fiorella/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Fiorella.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;


namespace Fiorella.Controllers
{
    public class BlogController : Controller
    {
        private readonly IBlogService _blogService;
        public BlogController(IBlogService blogService)
        {
            _blogService = blogService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _blogService.GetAllAsync());
        }
    }
}

Fiorella/Controllers/BlogDetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Fiorella.Models;
using Fiorella.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;


namespace Fiorella.Controllers
{
    public class BlogDetailController : Controller
    {
        private readonly IBlogService _blogService;
        public BlogDetailController(IBlogService blogService)
        {
            _blogService = blogService;
        }
        public async Task<IActionResult> Index(int? id)
        {
            if (id is null) return BadRequest();
            Blog blog = await _blogService.GetByIdAsync((int)id);
            if (blog is null) return NotFound();

            return View(blog);
        }
    }
}

Fiorella/Controllers/HomeController.cs
using System.Diagnostics;
using Fiorella.Services.Interfaces;
using Fiorella.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Fiorella.Controllers;

public class HomeController : Controller
{
    private readonly ISliderService _sliderService;
    private readonly IBlogService _blogService;
    private readonly IExpertService _expertService;
    private readonly ICategoryService _categoryService;
    private readonly IProductService _productService;

    public HomeController(ISliderService sliderService,
        IBlogService blogService,
        IExpertService expertService,
        ICategoryService categoryService,
        IProductService productService)
    {
        _sliderService = sliderService;
        _blogService = blogService;
        _expertService = expertService;
        _categoryService = categoryService;
        _productService = productService;
        
    }

    public async Task<IActionResult> Index()
    {
        HomeVM model = new()
        {
            Sliders = await _sliderService.GetAllAsync(),
            SliderInfo = await _sliderService.GetSliderInfoAsync(),
            Blogs = await _blogService.GetAllAsync(3),
            Experts = await _expertService.GetAllAsync(),
            Categories = await _categoryService.GetAllAsync(),
            Products = await _productService.GetAllAsync()
        };

        return View(model);
    }
}

Fiorella/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Fiorella.Models;
using Fiorella.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;


namespace Fiorella.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        public ProductController(IProductService productService)
        {
            _productService = productService;
        }
        public async Task<IActionResult> Index(int? id)
        {
            if (id is null) return BadRequest();
            Product product = await _productService.GetByIdAsync((int)id);
            if (product is null) return NotFound();

            return View(product);
        }
    }
}

Fiorella/Views/Blog/Index.cshtml
@model IEnumerable<BlogVM>

<section id="blog">
    <div class="container">
        <div class="row py-5">
            <div class="offset-lg-3 col-lg-6">
                <div class="section-title">
                    <h1>From our Blog</h1>
                    <p class="text-black-50">
                        A perfect blend of creativity, energy, communication, happiness and
                        love. Let us arrange
                        a smile for you.
                    </p>
                </div>
            </div>
        </div>
        <partial name="_BlogPartial" />
    </div>
</section>

Fiorella/Views/BlogDetail/Index.cshtml
@model Blog

@section css{
    <link rel="stylesheet" href="~/css/blogdetail.css">

}
<div class="container mt-5 mb-5">
    <div class="row d-flex justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="row">
                    <div class="col-md-6">
                        <div class="images p-3">
                            <div class="text-center p-4">
                            <img id="main-image" src="~/img/@Model.Image" width="250" />
                            </div>
                            @*<div class="thumbnail text-center">
                            <img onclick="change_image(this)" src="https://i.imgur.com/Rx7uKd0.jpg" width="70">
                            <img onclick="change_image(this)" src="https://i.imgur.com/Dhebu4F.jpg" width="70">
                            </div>*@
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="product p-4">
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="d-flex align-items-center"> <i class="fa fa-long-arrow-left"></i> <span class="ml-1"><a asp-controller="Blog" asp-action="Index">Back</a></span> </div> <i class="fa fa-shopping-cart text-muted"></i>
                            </div>
                            <div class="mt-4 mb-3">
                                <span class="text-uppercase text-muted brand">@Model.Title</span>
                                <!--<h5 class="text-uppercase">Men's slim fit t-shirt</h5>-->
                                @*<div class="price d-flex flex-row align-items-center">
                                    <span class="act-price">$20</span>
                                    <div class="ml-2"> <small class="dis-price">$59</small> <span>40% OFF</span> </div>
                                </div>*@
                            </div>
                            <p class="about">@Model.Description</p>
                            <div class="sizes mt-5">
                                <h6 class="text-uppercase">Size</h6> <label class="radio"> <input type="radio" name="size" value="S" checked> <span>S</span> </label> <label class="radio"> <input type="radio" name="size" value="M"> <span>M</span> </label> <label class="radio"> <input type="radio" name="size" value="L"> <span>L</span> </label> <label class="radio"> <input type="radio" name="size" value="XL"> <span>XL</span> </label> <label class="radio"> <input type="radio" name="size" value="XXL"> <span>XXL</span> </label>
                            </div>
                            <div class="cart mt-4 align-items-center"> <button class="btn btn-danger text-uppercase mr-2 px-4">Add to cart</button> <i class="fa fa-heart text-muted"></i> <i class="fa fa-share-alt text-muted"></i> </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>function change_image(image) {

        var container = document.getElementById("main-image");

        container.src = image.src;
    }



    document.addEventListener("DOMContentLoaded", function (event) {







    });</script>

Fiorella/Views/Home/Index.cshtml
@model HomeVM

    <!-- MAIN START -->

<main>

    <!-- SLIDER START -->

    <section id="slider">
        <div class="owl-carousel slider">
            @foreach (var item in Model.Sliders)
            {
                <div> <img src="~/img/@item.Image" alt=""> </div>

            }

        </div>
        <div class="container context pl-lg-5 ml-lg-3">
            <div class="row">
                <div class="col-lg-5">
                    <div class="text">
                        @Html.Raw(Model.SliderInfo.Title)
                        <p class="text-black-50 d-none d-sm-block">@Model.SliderInfo.Description</p>
                    </div>
                    <div class="img">
                        <img src="~/img/@Model.SliderInfo.Image" alt="">
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- SLIDER END -->
    <!-- PRODUCTS START -->

    <section id="products">
        <div class="container">
            <div class="row pt-5">
                <div class="col-12 d-flex justify-content-between">
                    <ul class="category-mobile d-md-none list-unstyled">
                        <li>
                            <a href="" class="categories mr-2">Categories</a>
                            <i class="fas fa-caret-down"></i>
                            <ul class="category list-unstyled" style="display: none;">
                                <li><a href="" data-id="all">All</a></li>
                                <li><a href="" data-id="popular">Popular</a></li>
                                <li><a href="" data-id="winter">Winter</a></li>
                                <li><a href="" data-id="various">Various</a></li>
                                <li><a href="" data-id="exotic">Exotic</a></li>
                                <li><a href="" data-id="green">Greens</a></li>
                                <li><a href="" data-id="cactuse">Cactuses</a></li>
                            </ul>
                        </li>
                    </ul>
                    <ul class="category d-none d-md-flex list-unstyled">
                        <li><a href="" data-id="all">All</a></li>
                        @foreach (var item in Model.Categories)
                        {
                            <li><a href="" data-id="@item.Id">@item.Name</a></li>
                        }
                    </ul>
                    <ul class="list-unstyled">
                        <li>
                            <a href="" class="mr-2">Filter</a>
                            <i class="fas fa-caret-down"></i>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="row">
                @foreach (var item in Model.Products)
                {
                    <div class="col-sm-6 col-md-4 col-lg-3 mt-3">
                        <div class="product-item text-center" data-id="@item.CategoryId">
                            <div class="img">
                                <a asp-controller="Product" asp-action="Index" asp-route-id="@item.Id">
                                    <img src="~/img/@item.ProductImages.FirstOrDefault(m=>m.IsMain)?.Name" class="img-fluid" alt="">
                                </a>
                            </div>
                            <div class="title mt-3">
                                <h6>@item.Name</h6>
                            </div>
                            <div class="price">
                                <span class="text-black-50">Add to cart</span>
                                <span class="text-black-50">$@item.Price.ToString(item.Price%1==0?"0":"0.00")</span>
                            </div>
                        </div>
                    </div>
                }

            </div>
        </div>
    </section>

    <!-- PRODUCTS END -->
    <!-- ABOUT START -->

    <section id="about">
        <div class="container py-5">
            <div class="row py-5">
                <div class="col-lg-6">
                    <div class="img">
                        <img src="~/img/h3-video-img.jpg" class="img-fluid" alt="">
                        <div class="player position-absolute rounded-circle d-flex align-items-center justify-content-center">
                            <i class="fas fa-play fa-lg"></i>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="about-text mt-5 mt-lg-0 px-lg-5">
                        <h1>Suprise Your <span>Valentine!</span> Let us arrange a smile.</h1>
                        <p class="py-3">
                            Where flowers are our inspiration to create lasting memories. Whatever the
                            occasion...
                        </p>
                        <ul class="list-unstyled">
                            <li class="mt-3">
                                <img src="~/img/h1-custom-icon.png" class="mr-2" alt=""> Hand picked just
                                for you.
                            </li>
                            <li class="mt-3">
                                <img src="~/img/h1-custom-icon.png" class="mr-2" alt=""> Unique flower
                                arrangements
                            </li>
                            <li class="mt-3">
                                <img src="~/img/h1-custom-icon.png" class="mr-2" alt=""> Best way to say
                                you care.
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- ABOUT END -->
    <!-- EXPERTS START -->

    <section id="experts">
        <div class="container">
            <div class="row py-5">
                <div class="offset-lg-3 col-lg-6">
                    <div class="section-title">
                        <h1>Flower Experts</h1>
                        <p class="text-black-50">
                            A perfect blend of creativity, energy, communication, happiness and
                            love. Let us arrange
                            a smile for you.
                        </p>
                    </div>
                </div>
            </div>
            <div class="row pb-5">
                @foreach (var item in Model.Experts)
                {
                    <div class="col-md-6 col-lg-3">
                        <div class="item text-center">
                            <div class="img">
                                <img src="~/img/@item.Image" class="img-fluid rounded-circle" alt="">
                            </div>
                            <div class="text mt-3">
                                <h6>@item.FullName</h6>
                                <p class="text-black-50">@item.Position</p>
                            </div>
                        </div>
                    </div>
                }

                <div class="col-lg-3"></div>
                <div class="col-lg-3"></div>
                <div class="col-lg-3"></div>
            </div>
        </div>
    </section>

    <!-- EXPERTS END -->
    <!-- SUBSCRIBE START -->

    <section id="subscribe">
        <div class="container py-5">
            <div class="row py-5">
                <div class="col-12">
                    <div class="content text-center py-5">
                        <h3>Join The Colorful Bunch!</h3>
                        <div class="form-group d-flex justify-content-center flex-wrap mt-5">
                            <input type="email" placeholder="Email Address" class="form-control-lg rounded-0">
                            <button class="btn btn-danger btn-lg rounded-0 px-5 mt-3 mt-sm-0">Subscribe</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- SUBSCRIBE END -->
    <!-- BLOG START -->

    <section id="blog">
        <div class="container">
            <div class="row py-5">
                <div class="offset-lg-3 col-lg-6">
                    <div class="section-title">
                        <h1>From our Blog</h1>
                        <p class="text-black-50">
                            A perfect blend of creativity, energy, communication, happiness and
                            love. Let us arrange
                            a smile for you.
                        </p>
                    </div>
                </div>
            </div>
            <partial name="_BlogPartial" model="@Model.Blogs" />
        </div>
    </section>

    <!-- BLOG END -->
    <!-- SAY START -->

    <section id="say">
        <div class="container">
            <div class="row py-5 justify-content-center">
                <div class="col-md-8 col-xl-6">
                    <div class="owl-carousel say">
                        <div>
                            <div class="item text-center">
                                <div class="img d-flex justify-content-center">
                                    <img src="~/img/testimonial-img-1.png" alt="">
                                </div>
                                <div class="text text-muted pt-3 pb-5">
                                    <i>
                                        Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus
                                        lingua.
                                    </i>
                                </div>
                                <div class="author">
                                    <h6>Anna Barnes</h6>
                                    <p class="text-black-50">Florist</p>
                                </div>
                            </div>
                        </div>
                        <div>
                            <div class="item text-center">
                                <div class="img d-flex justify-content-center">
                                    <img src="~/img/testimonial-img-2.png" alt="">
                                </div>
                                <div class="text text-muted pt-3 pb-5">
                                    <i>
                                        Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo
                                        ligula eget.
                                    </i>
                                </div>
                                <div class="author">
                                    <h6>Jasmine White</h6>
                                    <p class="text-black-50">Florist</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- SAY END -->
    <!-- INSTAGRAM START -->

    <section id="instagram">
        <div class="owl-carousel instagram">
            <div><img src="~/img/instagram1.jpg" class="img-fluid" alt=""></div>
            <div><img src="~/img/instagram2.jpg" class="img-fluid" alt=""></div>
            <div><img src="~/img/instagram3.jpg" class="img-fluid" alt=""></div>
            <div><img src="~/img/instagram4.jpg" class="img-fluid" alt=""></div>
            <div><img src="~/img/instagram5.jpg" class="img-fluid" alt=""></div>
            <div><img src="~/img/instagram6.jpg" class="img-fluid" alt=""></div>
            <div><img src="~/img/instagram7.jpg" class="img-fluid" alt=""></div>
            <div><img src="~/img/instagram8.jpg" class="img-fluid" alt=""></div>
        </div>
        <div class="hastag bg-light text-muted py-2 px-3">
            #FIORELLO
        </div>
    </section>

    <!-- INSTAGRAM END -->

</main>

<!-- MAIN END -->

Fiorella/Views/Product/Index.cshtml
@model Product

@section css{
    <link rel="stylesheet" href="~/css/product.css">

}

<div class="container mt-5 mb-5">
    <div class="row d-flex justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="row">
                    <div class="col-md-6">
                        <div class="images p-3">
                            <div class="text-center p-4"> <img id="main-image" src="~/img/@Model.ProductImages.FirstOrDefault(m=>m.IsMain)?.Name" width="250" /> </div>
                            <div class="thumbnail text-center">
                                @foreach (var item in Model.ProductImages)
                                {
                                    <img onclick="change_image(this)" src="~/img/@item.Name" width="70">

                                }
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="product p-4">
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="d-flex align-items-center"> <i class="fa fa-long-arrow-left"></i> <span class="ml-1"><a asp-controller="Home" asp-action="Index">Back</a></span> </div> <i class="fa fa-shopping-cart text-muted"></i>
                            </div>
                            <div class="mt-4 mb-3">
                                <span class="text-uppercase text-muted brand">@Model.Category.Name</span>
                                <h5 class="text-uppercase">@Model.Name</h5>
                                <div class="price d-flex flex-row align-items-center">
                                    <span class="act-price">$@Model.Price.ToString(@Model.Price % 1 == 0 ? "0" : "0.00")</span>
                                    <div class="ml-2"> <small class="dis-price">$59</small> <span>40% OFF</span> </div>
                                </div>
                            </div>
                            <p class="about">@Model.Description</p>
                            <div class="sizes mt-5">
                                <h6 class="text-uppercase">Size</h6> <label class="radio"> <input type="radio" name="size" value="S" checked> <span>S</span> </label> <label class="radio"> <input type="radio" name="size" value="M"> <span>M</span> </label> <label class="radio"> <input type="radio" name="size" value="L"> <span>L</span> </label> <label class="radio"> <input type="radio" name="size" value="XL"> <span>XL</span> </label> <label class="radio"> <input type="radio" name="size" value="XXL"> <span>XXL</span> </label>
                            </div>
                            <div class="cart mt-4 align-items-center"> <button class="btn btn-danger text-uppercase mr-2 px-4">Add to cart</button> <i class="fa fa-heart text-muted"></i> <i class="fa fa-share-alt text-muted"></i> </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    function change_image(image) {

        var container = document.getElementById("main-image");

        container.src = image.src;
    }



    document.addEventListener("DOMContentLoaded", function (event) {







    });
</script>

Fiorella/Views/Shared/_BlogPartial.cshtml
@model IEnumerable<BlogVM>


<div class="row pb-5">
    @foreach (var item in Model)
    {
        <div class="col-md-6 col-lg-4">
            <div class="item">
                <div class="img position-relative">
                    <a asp-controller="BlogDetail" asp-action="Index" asp-route-id="@item.Id">
                        <img src="~/img/@item.Image" class="img-fluid" alt="">
                    </a>
                    <div class="date rounded bg-light position-absolute py-1 px-2">
                        <span>@item.CreatedDate</span>
                    </div>
                </div>
                <div class="text mt-3 text-center px-5">
                    <h5>@item.Title</h5>
                    <p class="text-black-50">
                        @item.Description
                    </p>
                </div>
            </div>
        </div>

    }

</div>